
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'


stages:
  - stage: build
    jobs:
      - job: recupere_code
        steps:
          - script: |
              npm install
              sleep 5
              npm run build 

      - job: preparer_dockerfile
        steps:
         #  - checkout: self
           - task: Docker@2
             inputs:
              command: login
              containerRegistry: dockerAuth

        
           - script: |
              docker build -t  brahimbtf/frontedn0123456  . 
              sleep 5
              docker push brahimbtf/frontedn0123456 




